### ISSUE TITLE
User Disconnects from Page

### ISSUE THREAD

**Issue by NealMatta** [NealMatta/Mafia#13]
- Problem
When a user disconnects from a page, they still appear in the list of all players

- How To Recreate
Open two windows - one in incognito and one normal and join into the same room. In one window, exit out of the screen and you should see 'user disconnected' in the console. Then if you refresh the page in the other screen, you should still see both users

**Comment by AK97** [comment]
### Fixed
In pregame lobbies, player list will drop and add players as they come and go.

### Caveat
In in-game lobbies, player list currently remains populated with everyone the game started with. The public chat will notify everyone of disconnects, but the player list stays static so the full list of players in the game (potentially with roles, and those who will be included in kill votes)
