### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by NealMatta** [NealMatta/Mafia#15]
### Problem
Testing the functionality involves having 4 browsers open and constantly refreshing the page. Should be an easier and simpler way to test the functionality 

### Solution 
[Link 1](https://stackoverflow.com/questions/15509231/unit-testing-node-js-and-websockets-socket-io)
[Link 2](https://artillery.io/docs/socketio-reference/)

**Comment by AK97** [comment]
Another possible solution is [SocketBox](https://sessionbox.io/).

It seems like it would allow us to open multiple tabs in Chrome that access the site as if we are multiple users. It's not THAT much easier that opening multiple browsers but it's the only way i can imagine testing multiple users using just one computer without needing 4+ browsers

**Comment by NealMatta** [comment]
Cannot find something that will work for us
